// src/layouts/infinite-canvas/WindowLayer.vue
<script setup lang="ts">
/**
 * 窗口层组件
 * @module layouts/infinite-canvas/WindowLayer
 * @description 渲染工具窗口（不受缩放影响），集成程序坞
 */

import { computed } from 'vue';
import { ToolWindow } from '@/components/window';
import { Dock } from '@/components/dock';
import { useUIStore } from '@/core/state';
import { useWindowManager } from '@/core/window-manager';
import type { ToolWindowConfig } from '@/types';

const emit = defineEmits<{
  /** 转发 Dock 的打开设置事件 */
  'open-settings': [];
}>();

const uiStore = useUIStore();
const windowManager = useWindowManager();

/** 获取工具窗口（在窗口层显示，不最小化的） */
const toolWindows = computed(() =>
  uiStore.toolWindows.filter((w) => w.state !== 'minimized')
);

/**
 * 处理工具窗口更新
 * @param windowId - 窗口 ID
 * @param updates - 更新内容
 */
function handleToolWindowUpdate(windowId: string, updates: Partial<ToolWindowConfig>): void {
  windowManager.updateWindow(windowId, updates);
}

/**
 * 处理工具窗口关闭
 * @param windowId - 窗口 ID
 */
function handleToolWindowClose(windowId: string): void {
  windowManager.closeWindow(windowId);
}

/**
 * 处理工具窗口聚焦
 * @param windowId - 窗口 ID
 */
function handleToolWindowFocus(windowId: string): void {
  windowManager.focusWindow(windowId);
}
</script>

<template>
  <div class="window-layer">
    <!-- 工具窗口 -->
    <ToolWindow
      v-for="window in toolWindows"
      :key="window.id"
      :config="window"
      @update:config="(updates) => handleToolWindowUpdate(window.id, updates)"
      @close="handleToolWindowClose(window.id)"
      @focus="handleToolWindowFocus(window.id)"
    >
      <!-- 动态组件插槽 -->
      <slot :name="`tool-${window.component}`" :config="window"></slot>
    </ToolWindow>

    <!-- 其他窗口层内容插槽 -->
    <slot></slot>

    <!-- 程序坞组件 -->
    <Dock @open-settings="emit('open-settings')" />
  </div>
</template>

<style scoped>
.window-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
}

.window-layer > :deep(*) {
  pointer-events: auto;
}
</style>

// src/layouts/infinite-canvas/WindowLayer.tsx
import React, { useCallback, type ReactNode } from 'react';
import { ToolWindow } from '@/components/window';
import { Dock } from '@/components/dock';
import { useUIStore } from '@/core/state';
import { useWindowManager } from '@/core/window-manager';
import type { ToolWindowConfig } from '@/types';
import './WindowLayer.css';

export interface WindowLayerProps {
    children?: ReactNode;
    onOpenSettings?: () => void;
    // TODO: Vue version had dynamic slot for each tool component
    // In React, we might want a renderProp or context
}

export function WindowLayer({ children, onOpenSettings }: WindowLayerProps) {
    // 获取处于非最小化状态的工具窗口
    const toolWindows = useUIStore((s) =>
        s.windowList.filter((w): w is ToolWindowConfig => w.type === 'tool' && w.state !== 'minimized')
    );

    const windowManager = useWindowManager();

    const handleToolWindowUpdate = useCallback((windowId: string, updates: Partial<ToolWindowConfig>) => {
        windowManager.updateWindow(windowId, updates);
    }, [windowManager]);

    const handleToolWindowClose = useCallback((windowId: string) => {
        windowManager.closeWindow(windowId);
    }, [windowManager]);

    const handleToolWindowFocus = useCallback((windowId: string) => {
        windowManager.focusWindow(windowId);
    }, [windowManager]);

    return (
        <div className="window-layer">
            {/* 工具窗口 */}
            {toolWindows.map((window) => (
                <ToolWindow
                    key={window.id}
                    config={window}
                    onUpdateConfig={(updates) => handleToolWindowUpdate(window.id, updates)}
                    onClose={() => handleToolWindowClose(window.id)}
                    onFocus={() => handleToolWindowFocus(window.id)}
                >
                    {/* React 版本动态组件，之后需要专门的注册机或者组件 Map 来渲染 content */}
                    {/* 这里简单展示暂位符，或直接通过插件注册的 map 渲染 */}
                    <div style={{ padding: '8px', color: '#666' }}>
                        [{window.component} Plugin Context]
                    </div>
                </ToolWindow>
            ))}

            {/* 其他窗口层内容 */}
            {children}

            {/* 程序坞 */}
            <Dock onOpenSettings={onOpenSettings} />
        </div>
    );
}
