// src/components/engine-settings/panels/ToolsSettingsPanel.vue
<script setup lang="ts">
/**
 * 工具管理设置面板
 * @module components/engine-settings/panels/ToolsSettingsPanel
 *
 * 管理编辑引擎中已安装的工具和插件。
 * 支持启用、禁用和安装新工具。
 *
 * 使用薯片组件库，遵循主题系统规范，使用 --chips-* CSS 变量
 */

import { ref, onMounted } from 'vue';
import { Button, Switch } from '@chips/components';
import { t } from '@/services/i18n-service';

/** 工具信息（从 SDK.PluginManager 获取） */
interface ToolInfo {
  id: string;
  name: string;
  version: string;
  author?: string;
  description?: string;
  enabled: boolean;
}

/** 工具列表 */
const tools = ref<ToolInfo[]>([]);

/** 加载状态 */
const isLoading = ref(false);

/**
 * 加载工具列表
 */
async function loadTools(): Promise<void> {
  isLoading.value = true;
  try {
    // TODO: 从 SDK.PluginManager 获取工具列表
    // const sdk = await getEditorSdk();
    // const plugins = sdk.plugins.list();
    // tools.value = plugins.map(p => ({ ... }));
    tools.value = [];
  } finally {
    isLoading.value = false;
  }
}

/**
 * 切换工具启用状态
 */
function handleToggleTool(_toolId: string, _enabled: boolean): void {
  // TODO: 调用 SDK.PluginManager 切换工具状态
}

onMounted(() => {
  loadTools();
});
</script>

<template>
  <div class="tools-settings-panel">
    <!-- 标题 -->
    <div class="settings-panel-header">
      <h3 class="settings-panel-header__title">
        {{ t('engine_settings.tools_title') }}
      </h3>
      <p class="settings-panel-header__desc">
        {{ t('engine_settings.tools_description') }}
      </p>
    </div>

    <!-- 已安装工具列表 -->
    <div class="settings-field">
      <div class="settings-field__header">
        <label class="settings-field__label">
          {{ t('engine_settings.tools_installed') }}
        </label>
      </div>

      <!-- 空状态 -->
      <div v-if="tools.length === 0 && !isLoading" class="settings-empty">
        <span class="settings-empty__icon">🧩</span>
        <span class="settings-empty__text">
          {{ t('engine_settings.tools_no_tools') }}
        </span>
      </div>

      <!-- 工具列表 -->
      <div v-else class="tools-list">
        <div
          v-for="tool in tools"
          :key="tool.id"
          class="tool-item"
        >
          <div class="tool-item__info">
            <span class="tool-item__name">{{ tool.name }}</span>
            <span class="tool-item__meta">
              {{ t('engine_settings.tools_version') }}: {{ tool.version }}
              <template v-if="tool.author">
                &middot; {{ t('engine_settings.tools_author') }}: {{ tool.author }}
              </template>
            </span>
            <span v-if="tool.description" class="tool-item__desc">
              {{ tool.description }}
            </span>
          </div>
          <Switch
            :model-value="tool.enabled"
            @update:model-value="(val: boolean) => handleToggleTool(tool.id, val)"
          />
        </div>
      </div>
    </div>

    <!-- 安装新工具 -->
    <div class="settings-actions">
      <Button type="default" html-type="button">
        {{ t('engine_settings.tools_install') }}
      </Button>
    </div>
  </div>
</template>

<style scoped>
@import '../styles/settings-panel.css';

.tools-list {
  display: flex;
  flex-direction: column;
  gap: var(--chips-spacing-sm, 8px);
}

.tool-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--chips-spacing-sm, 12px) var(--chips-spacing-md, 16px);
  border: 1px solid var(--chips-color-border, #e5e7eb);
  border-radius: var(--chips-radius-md, 8px);
  background: var(--chips-color-surface, #ffffff);
}

.tool-item__info {
  display: flex;
  flex-direction: column;
  gap: 2px;
  flex: 1;
  min-width: 0;
  margin-right: var(--chips-spacing-md, 16px);
}

.tool-item__name {
  font-size: var(--chips-font-size-sm, 14px);
  font-weight: var(--chips-font-weight-medium, 500);
  color: var(--chips-color-text, #111827);
}

.tool-item__meta {
  font-size: 12px;
  color: var(--chips-color-text-secondary, #6b7280);
}

.tool-item__desc {
  font-size: 12px;
  color: var(--chips-color-text-secondary, #6b7280);
  margin-top: 2px;
}
</style>

// src/components/engine-settings/panels/ToolsSettingsPanel.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { ChipsButton, ChipsSwitch } from '@chips/component-library';
import { invokeEditorRuntime } from '@/services/editor-runtime-gateway';
import { t } from '@/services/i18n-service';
import '../styles/settings-panel.css';

/** 工具信息（从 SDK.PluginManager 获取） */
interface ToolInfo {
  id: string;
  name: string;
  version: string;
  type: string;
  author?: string;
  description?: string;
  enabled: boolean;
}

/**
 * 工具管理设置面板
 * 管理编辑引擎中已安装的工具和插件。
 * 支持启用、禁用和安装新工具。
 */
export function ToolsSettingsPanel() {
  /** 工具列表 */
  const [tools, setTools] = useState<ToolInfo[]>([]);

  /** 加载状态 */
  const [isLoading, setIsLoading] = useState(false);

  /**
   * 加载工具列表
   */
  const loadTools = useCallback(async () => {
    setIsLoading(true);
    try {
      const response = await invokeEditorRuntime<{
        plugins?: Array<{
          id: string;
          name?: string;
          version?: string;
          type?: string;
          publisher?: string;
          description?: string;
          enabled: boolean;
        }>;
      }>('plugin', 'list', {});

      const plugins = Array.isArray(response.plugins) ? response.plugins : [];
      setTools(plugins.map((plugin) => ({
        id: plugin.id,
        name: plugin.name?.trim() || plugin.id,
        version: plugin.version?.trim() || '0.0.0',
        type: plugin.type?.trim() || 'module',
        author: plugin.publisher?.trim() || undefined,
        description: plugin.description?.trim() || undefined,
        enabled: plugin.enabled === true,
      })));
    } catch (error) {
      console.error('Failed to load tools:', error);
      setTools([]);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadTools();
  }, [loadTools]);

  /**
   * 切换工具启用状态
   */
  const handleToggleTool = useCallback(async (toolId: string, enabled: boolean) => {
    try {
      const target = tools.find((tool) => tool.id === toolId);
      const type = target?.type;
      await invokeEditorRuntime('plugin', enabled ? 'enable' : 'disable', {
        pluginId: toolId,
        ...(type ? { type } : {}),
      });
      // 更新本地状态
      setTools((prevTools) =>
        prevTools.map((tool) =>
          tool.id === toolId ? { ...tool, enabled } : tool
        )
      );
    } catch (error) {
      console.error('Failed to toggle tool state:', error);
      await loadTools();
    }
  }, [tools, loadTools]);

  return (
    <div className="tools-settings-panel">
      {/* 标题 */}
      <div className="settings-panel-header">
        <h3 className="settings-panel-header__title">
          {t('engine_settings.tools_title')}
        </h3>
        <p className="settings-panel-header__desc">
          {t('engine_settings.tools_description')}
        </p>
      </div>

      {/* 已安装工具列表 */}
      <div className="settings-field">
        <div className="settings-field__header">
          <label className="settings-field__label">
            {t('engine_settings.tools_installed')}
          </label>
        </div>

        {/* 空状态 */}
        {tools.length === 0 && !isLoading && (
          <div className="settings-empty">
            <span className="settings-empty__icon">🧩</span>
            <span className="settings-empty__text">
              {t('engine_settings.tools_no_tools')}
            </span>
          </div>
        )}

        {/* 工具列表 */}
        {tools.length > 0 && (
          <div className="tools-list">
            {tools.map((tool) => (
              <div
                key={tool.id}
                className="tool-item"
              >
                <div className="tool-item__info">
                  <span className="tool-item__name">{tool.name}</span>
                  <span className="tool-item__meta">
                    {t('engine_settings.tools_version')}: {tool.version}
                    {tool.author && (
                      <> &middot; {t('engine_settings.tools_author')}: {tool.author}</>
                    )}
                  </span>
                  {tool.description && (
                    <span className="tool-item__desc">
                      {tool.description}
                    </span>
                  )}
                </div>
                <ChipsSwitch
                  checked={tool.enabled}
                  onChange={(val: boolean) => handleToggleTool(tool.id, val)}
                />
              </div>
            ))}
          </div>
        )}
      </div>

      {/* 安装新工具 */}
      <div className="settings-actions">
        <ChipsButton variant="default" htmlType="button">
          {t('engine_settings.tools_install')}
        </ChipsButton>
      </div>
    </div>
  );
}
